start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'safari'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'mail'
run = 'layout floating'


[gaps]
inner.horizontal = 7
inner.vertical = 7
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-shift-h = 'focus left'
ctrl-alt-shift-j = 'focus down'
ctrl-alt-shift-k = 'focus up'
ctrl-alt-shift-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-shift-cmd-h = 'move left'
ctrl-alt-shift-cmd-j = 'move down'
ctrl-alt-shift-cmd-k = 'move up'
ctrl-alt-shift-cmd-l = 'move right'
ctrl-alt-shift-w = 'exec-and-forget open -a /Applications/WezTerm.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-shift-cmd-minus = 'resize smart -50'
ctrl-alt-shift-cmd-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-alt-shift-1 = 'workspace 1'
ctrl-alt-shift-2 = 'workspace 2'
ctrl-alt-shift-3 = 'workspace 3'
ctrl-alt-shift-4 = 'workspace 4'
ctrl-alt-shift-5 = 'workspace 5'
ctrl-alt-shift-6 = 'workspace 6'
ctrl-alt-shift-7 = 'workspace 7'
ctrl-alt-shift-8 = 'workspace 8'
ctrl-alt-shift-9 = 'workspace 9'
ctrl-alt-shift-a = 'workspace prev'
ctrl-alt-shift-d = 'workspace next'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-alt-shift-cmd-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-shift-cmd-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-alt-shift-cmd-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-alt-shift-cmd-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-alt-shift-cmd-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-alt-shift-cmd-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-alt-shift-cmd-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-alt-shift-cmd-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-alt-shift-cmd-9 = ['move-node-to-workspace 9', 'workspace 9']
ctrl-alt-shift-cmd-a = ['move-node-to-workspace prev', 'workspace prev']
ctrl-alt-shift-cmd-d = ['move-node-to-workspace next', 'workspace next']

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-shift-cmd-semicolon = 'mode service'
# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
